### PR TITLE
Enumerate questions (continued #62)

### PR DESCRIPTION
**Pull request by jaguarfi**
# Description

Closes #62 

# Testing
I tested the changes manually. However, it is difficult to test the functionalities of the questionnaire due to the lack of documentation on the use cases.

# Have you updated the README or other relevant documentation?

the README file will be updated later on.

# Is it [Done](https://wiki.aalto.fi/display/EDIT/Definition+of+Done)?

- [ ] I (developer) have created unit tests and the tests pass
- [ ] I (developer) have created functional tests (Selenium tests) if applicable
- [X] I (developer) have tested the changes manually
- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

### CODE REVIEW

**Comment by raphendyr** [comment]
Can you set e.g. the same title and you could add `closes #62` in the description, so these are automatically connected.

**Comment by jaguarfi** [comment]
@raphendyr, should I add the "Enumerate questions closes #62" also as the title of the PR? Or how should actually title a PR like this?

**Comment by raphendyr** [comment]
I'm not sure, but I think you could even use the same title, e.g., "Enumerate questions (continued)". Basically, title should always describe what this PR does (similar to how commits titles work).

**Comment by Mankro** [comment]
The other issue https://github.com/apluslms/a-plus/issues/490 might revamp the question hints so that this PR becomes irrelevant. Let's see how it progresses.

**Comment by Mankro** [comment]
I am closing this. This work has become outdated and the feature is not needed anymore. Since A+ v1.10, questionnaires may use the option `checkbox_feedback` in checkbox questions if they want to render the hint directly under the affected checkbox. This accomplishes a similar effect as the enumeration concerning how the hint is connected to each checkbox.

`checkbox_feedback`:
https://github.com/apluslms/mooc-grader/blob/ac73c32cef61d2cc7c425fccdb2bd0991d243b55/courses/README.md

I used this same message in #62:
https://github.com/apluslms/a-plus-rst-tools/pull/62#issuecomment-1171074701

**Pull request closed without merging**
