### PR TITLE
Add support for show-zero-points-immediately

### PR DESCRIPTION
**Pull request by mikaelGusse**
# Description

**What?**

Add support to rst-tools to enable the show-zero-points-immediately flag for an exercise. 

**Why?**

Was asked by the teachers. Needs the requisite A+ pull request to function correctly [A+ pr #1389](https://github.com/apluslms/a-plus/pull/1389)

**How?**

Changed revealrule.py parsing

# Testing

**Remember to add or update unit tests for new features and changes.**

* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations)
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull+requests)

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [x] Manual testing.

[ADD A DESCRIPTION ABOUT WHAT YOU TESTED MANUALLY]

**Did you test the changes in**

- [ ] Chrome
- [ ] Firefox
- [ ] This pull request cannot be tested in the browser.

**Think of what is affected by these changes and could become broken**

# Translation

- [ ] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [ ] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [ ] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

*Clean up your git commit history before submitting the pull request!*

### CODE REVIEW

**Review by ihalaij1 — COMMENTED** [review]
I don't know how I feel about this syntax with a `:` to split the option arguments.
What do you think @murhum1 ?

Should we just have a separate option, e.g., `:reveal-zero-points-immediately:` that gives a warning if the `:reveal-submission-feedback:` option is missing?

There is a somewhat similar validation with `:randomized:` and `:structured-randomized:` options, where the build fails if both are used at the same time:

https://github.com/apluslms/a-plus-rst-tools/blob/678f31303e6533874f6c2e87ad75558fd64fb595/directives/questionnaire.py#L514-L520

**Comment by murhum1** [comment]
Yep, I'd definitely prefer having it as a separate option to keep the syntax cleaner. I'll modify this to use that instead.

**Comment by murhum1** [comment]
@ihalaij1 I added show-zero-points-immediately as a separate option, and tested it to work locally. Can you check the changes?

**Review by ihalaij1 — APPROVED** [review]
I didn't test the new changes, but the code looks good! @murhum1

**Pull request merged**
