### PR TITLE
Add placeholder option for freetext

### PR DESCRIPTION
**Pull request by Mikael-Lenander**
# Description

**What?**

Add placeholder option for freetext directive. Placeholder is a text that is shown in an empty input field.

**Why?**

Specify units etc.

**How?**

Adds a new option_spec to FreeText class.

# Testing

**Remember to add or update unit tests for new features and changes.**

* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations)
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull+requests)

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [x] Manual testing.

Compiled rst code. The placeholder attributes appeared in html files in _build folder.

**Did you test the changes in**

- [ ] Chrome
- [ ] Firefox
- [ ] This pull request cannot be tested in the browser.

**Think of what is affected by these changes and could become broken**

# Translation

- [ ] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [x] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [ ] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [x] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

*Clean up your git commit history before submitting the pull request!*

### CODE REVIEW

**Comment by ihalaij1** [comment]
Related issue: apluslms/a-plus#1143

**Comment by Mikael-Lenander** [comment]
I looked into this in more detail and turns out that there is no need for an additional option in the FreeText class. The placeholder can be added to the :extra: option and it renders nicely. However, the placeholder is not added to form_i18n dictionary for some reason, so translations don't work.

**Comment by ihalaij1** [comment]
Hey,

I got the placeholder FreeText option working for multilingual courses, it required some changes in MOOC-Grader too.
I will be finishing a pull request on it and you can then test it.

**Comment by ihalaij1** [comment]
I believe I still need to do similar changes to MOOC-Jutut as I did to MOOC-Grader to get the placeholder to display in Jutut exercises too. I'll see if I can figure it out.

**Comment by ihalaij1** [comment]
@Mikael-Lenander I got the placeholder :extra: option working more easily, since it was already somewhat supported by MOOC-Jutut.
I had to make some changes in MOOC-Grader to get the translations working in both MOOC-Jutut questionnaires and normal MOOC-Grader questionnaires.

Could you test the PR and tell me if it fulfills your needs?
https://github.com/apluslms/mooc-grader/pull/157

I will close this PR now, since we don't need a new :placeholder: option after all.

**Pull request closed without merging**
