### PR TITLE
Add 'structured-randomized' option for checkbox questions

### PR DESCRIPTION
**Pull request by ihalaij1**
# Description

This new option allows teachers to group the checkbox choices into subgroups and to select a specific number of answer choices from each subgroup.

Random selection from one large pool could include only easy choices for some students and challenging choices for others, hence the teacher wants to ensure that the combined random selection includes some choices from each group.

The value of the option is a string expression of the format
`(pick X answer-choice-1 answer-choice-2 ...) (pick Y answer-choice-3 answer-choice-4 ...) ...`,
where `X` and `Y` are the number of choices to randomly select from their respective
groups of answer choices. Example: `(pick 1 a b) (pick 2 c d e f) (pick 1 g h)`.
The string expression may also include nested `pick` groups, e.g.,
`(pick 3 a b (pick 1 c d) e f)`. In this example, one of `c` or `d` is randomly picked first,
and then three answer choices are randomly picked from the pool of `a`, `b`, `c`, `e`, and `f`
or `a`, `b`, `d`, `e`, and `f`, depending how the choice between `c` and `d` played out.
The option `correct-count` should not be set when this option is used,
since the number of correct answer choices can be controlled using the structure.

This PR requires apluslms/compile-rst#7 due to regex pip package dependency.

There are conflicting changes with PR #175, but they should be easy to resolve.

**Why?**

This was requested by multiple teachers.

Part of apluslms/mooc-grader#120

# Testing

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [x] Manual testing.

Tested that the new option works correctly with different arguments, and that invalid arguments are detected.

**Did you test the changes in**

- [x] Chrome
- [ ] Firefox
- [ ] This pull request cannot be tested in the browser.

# Translation

- [ ] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [x] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [ ] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [x] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

### CODE REVIEW

**Comment by ihalaij1** [comment]
Added nested pick groups now, since it was emphasized by a teacher that it is needed and useful.

**Review by PasiSa — APPROVED** [review]
Did not find problems by reading the code, and the old 'randomized' variant seems to work as before. If you are happy with it, feel free to merge.

**Comment by jsorva** [comment]
Hi! Is it a known issue that this change causes the newly introduced duplicate checks to malfunction? 

That is, _"The choice keys in a questionnaire must be unique! Found a duplicate key"_ is produced on every questionnaire, if I try to build the O1 course on master now.

**Comment by ihalaij1** [comment]
> Hi! Is it a known issue that this change causes the newly introduced duplicate checks to malfunction?
> 
> That is, _"The choice keys in a questionnaire must be unique! Found a duplicate key"_ is produced on (seemingly) every questionnaire, if I try to build the O1 course on master now.

Hey! Thanks for pointing that out, it is now fixed!

**Pull request merged**
